language: node_js
node_js:
  - "6"
install:
    - npm install
script:
    - npm run unit
after_success:
  - npm run build
  - test $TRAVIS_BRANCH = "master" && surge --project ./dist --domain plannr.space


